---
- name: create app dir ~/install-docker/
  file:
    state: directory
    path: "/home/{{ ansible_user }}/install-docker/"
    owner: "{{ ansible_user }}"
  register: deploy_dir
- name: Copy install files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "../../../setup/setup_docker.sh", dest: "{{ deploy_dir.path }}"     }
- name: Run shell instance-startup.sh
  ansible.builtin.shell: /bin/sh "{{ deploy_dir.path }}instance-startup.sh" >> instance_startup_log.txt
  register: out
- name: shell output
  debug: var=out.stdout